"""initial schema

Revision ID: 16c0839dcd73
Revises: a2005268e50c
Create Date: 2026-02-26 19:22:10.872789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16c0839dcd73'
down_revision: Union[str, Sequence[str], None] = 'a2005268e50c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'candidates', ['id'])
    op.create_unique_constraint(None, 'educations', ['id'])
    op.create_unique_constraint(None, 'experiences', ['id'])
    op.create_unique_constraint(None, 'projects', ['id'])
    op.create_unique_constraint(None, 'recruiters', ['id'])
    op.create_unique_constraint(None, 'skills', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skills', type_='unique')
    op.drop_constraint(None, 'recruiters', type_='unique')
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_constraint(None, 'experiences', type_='unique')
    op.drop_constraint(None, 'educations', type_='unique')
    op.drop_constraint(None, 'candidates', type_='unique')
    # ### end Alembic commands ###
