"""initial_schema

Revision ID: 21659fcad438
Revises: d1c4f2702291
Create Date: 2026-02-27 13:35:18.493752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21659fcad438'
down_revision: Union[str, Sequence[str], None] = 'd1c4f2702291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('maching_role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'maching_role')
    # ### end Alembic commands ###
