"""

Revision ID: b7cc1cfa77e7
Revises: 0881ab227b9f
Create Date: 2026-02-28 21:32:56.010929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7cc1cfa77e7'
down_revision: Union[str, Sequence[str], None] = '0881ab227b9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resumes', 'selection_status',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', name='selection_status_enum'),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resumes', 'selection_status',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', name='selection_status_enum'),
               server_default=sa.text("'PENDING'::selection_status_enum"),
               existing_nullable=False)
    # ### end Alembic commands ###
