"""initial_schema

Revision ID: d1c4f2702291
Revises: a436c0ea1871
Create Date: 2026-02-27 02:43:31.248949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1c4f2702291'
down_revision: Union[str, Sequence[str], None] = 'a436c0ea1871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'candidates', ['id'])
    op.create_unique_constraint(None, 'educations', ['id'])
    op.create_unique_constraint(None, 'experiences', ['id'])
    op.create_unique_constraint(None, 'projects', ['id'])
    op.create_unique_constraint(None, 'recruiters', ['id'])
    op.create_unique_constraint(None, 'skills', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skills', type_='unique')
    op.drop_constraint(None, 'recruiters', type_='unique')
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_constraint(None, 'experiences', type_='unique')
    op.drop_constraint(None, 'educations', type_='unique')
    op.drop_constraint(None, 'candidates', type_='unique')
    # ### end Alembic commands ###
